"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Brain, Gamepad2, Lightbulb, CheckCircle2, XCircle, RefreshCw, ChevronRight, Trophy, Bot, User, Sparkles } from 'lucide-react';

interface Question {
  question: string;
  options: string[];
  answerIdx: number;
  explanation: string;
}

interface GuessItem {
  prompt: string;
  isAi: boolean;
  type: string;
  explanation: string;
}

interface Fact {
  title: string;
  emoji: string;
  content: string;
}

export default function AiPlayground() {
  const [activeMode, setActiveMode] = useState<'quiz' | 'game' | 'facts'>('quiz');

  // Mode 1: Quiz (Trivia Challenge)
  const quizQuestions: Question[] = [
    {
      question: "Which of these helps a self-driving car 'see' its surroundings?",
      options: ["Lidar sensors & cameras", "A magnifying glass", "A tiny remote control", "Magical flashlight eyes"],
      answerIdx: 0,
      explanation: "Self-driving cars use advanced Lidar (light detection and ranging) and camera sensors combined with AI to build a 3D model of their surroundings."
    },
    {
      question: "How does an artificial intelligence learn to recognize a dog?",
      options: ["By reading dictionary definitions", "By studying millions of dog images", "It is born knowing it", "By asking cats"],
      answerIdx: 1,
      explanation: "AI learns through machine learning by looking at massive datasets (millions of photos) and discovering common patterns that define a 'dog'."
    },
    {
      question: "Which of these is NOT something AI can currently do?",
      options: ["Write computer code", "Paint beautiful digital artwork", "Feel real human emotions", "Compose pop songs"],
      answerIdx: 2,
      explanation: "While AI can generate text, art, and code, it does not possess consciousness, feelings, or genuine human emotions."
    }
  ];

  const [currentQuizIdx, setCurrentQuizIdx] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [quizScore, setQuizScore] = useState(0);
  const [quizFinished, setQuizFinished] = useState(false);

  // Mode 2: Game (AI vs Human Artist)
  const guessItems: GuessItem[] = [
    {
      prompt: '"A magical forest glowing with trees made of computer chips and digital code, under a bright neon crescent moon."',
      isAi: true,
      type: "Art Description",
      explanation: "This surreal creative prompt was entirely written by ChatGPT to guide an AI art generator!"
    },
    {
      prompt: '"Once upon a time in a byte-sized world, a little pixel named Dot got lost in a complex recursive loop..."',
      isAi: true,
      type: "Story Snippet",
      explanation: "This coding-themed bedtime story was generated by a generative AI model in less than 2 seconds."
    },
    {
      prompt: '"Starry Night: A painting of swirling blue and yellow clouds over a sleeping village."',
      isAi: false,
      type: "Historical Artwork",
      explanation: "This classic masterpiece was painted by Vincent van Gogh in 1889, long before computers existed!"
    }
  ];

  const [currentGameIdx, setCurrentGameIdx] = useState(0);
  const [guessAnswered, setGuessAnswered] = useState<boolean | null>(null);
  const [isCorrectGuess, setIsCorrectGuess] = useState<boolean | null>(null);
  const [gameScore, setGameScore] = useState(0);
  const [gameFinished, setGameFinished] = useState(false);

  // Mode 3: Facts
  const facts: Fact[] = [
    {
      title: "AI Translates Whale Speech!",
      emoji: "🐋",
      content: "Scientists are currently training AI algorithms to translate the clicks and whistles of sperm whales into human languages so we can communicate with them."
    },
    {
      title: "AI Writes 40% of Code!",
      emoji: "💻",
      content: "Tools like GitHub Copilot are so widely used that over 40% of the code in modern software programs is now suggested or written by AI helpers."
    },
    {
      title: "The First Robot in 1920!",
      emoji: "🤖",
      content: "The word 'Robot' was first introduced in a science fiction play by Czech writer Karel Čapek in 1920. It comes from the Czech word 'robota', meaning forced labor."
    },
    {
      title: "Microsecond Recognition!",
      emoji: "⚡",
      content: "Modern facial-recognition AI can analyze more than 100 features of a human face to verify an identity in less than a single microsecond."
    }
  ];
  const [currentFactIdx, setCurrentFactIdx] = useState(0);

  useEffect(() => {
    // Pick a random fact index on mount
    setCurrentFactIdx(Math.floor(Math.random() * facts.length));
  }, []);

  const showNextFact = () => {
    let nextIdx;
    do {
      nextIdx = Math.floor(Math.random() * facts.length);
    } while (nextIdx === currentFactIdx && facts.length > 1);
    setCurrentFactIdx(nextIdx);
  };

  // Resets
  const resetQuiz = () => {
    setCurrentQuizIdx(0);
    setSelectedOption(null);
    setQuizScore(0);
    setQuizFinished(false);
  };

  const resetGame = () => {
    setCurrentGameIdx(0);
    setGuessAnswered(null);
    setIsCorrectGuess(null);
    setGameScore(0);
    setGameFinished(false);
  };

  return (
    <section className="py-16 md:py-24 px-4 bg-slate-50 border-t border-b border-slate-100 overflow-hidden" id="ai-playground">
      <div className="max-w-6xl mx-auto">
        
        {/* Header */}
        <div className="text-center mb-10 md:mb-14">
          <span className="text-xs font-black text-[#00ACC1] uppercase tracking-widest block mb-3 animate-pulse">
            Interactive Playground
          </span>
          <h2 className="font-baloo text-3xl md:text-5xl font-black text-slate-900 leading-tight">
            Play & Learn <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-500">AI Basics</span>
          </h2>
          <p className="text-slate-500 font-bold mt-4 text-sm sm:text-base max-w-xl mx-auto">
            Test your knowledge, play our creative guessing game, or discover mind-blowing artificial intelligence facts!
          </p>
        </div>

        {/* Navigation Tabs */}
        <div className="flex justify-center p-1.5 bg-white border border-slate-200/60 rounded-2xl sm:rounded-full max-w-lg mx-auto mb-10 md:mb-12 shadow-sm">
          <button
            onClick={() => setActiveMode('quiz')}
            className={`flex-1 py-3 px-4 rounded-xl sm:rounded-full text-xs sm:text-sm font-black transition-all flex items-center justify-center gap-1.5 ${
              activeMode === 'quiz'
                ? 'bg-[#0D47A1] text-white shadow-sm'
                : 'text-slate-500 hover:text-slate-900'
            }`}
          >
            <Brain size={16} /> Trivia Quiz
          </button>
          <button
            onClick={() => setActiveMode('game')}
            className={`flex-1 py-3 px-4 rounded-xl sm:rounded-full text-xs sm:text-sm font-black transition-all flex items-center justify-center gap-1.5 ${
              activeMode === 'game'
                ? 'bg-[#0D47A1] text-white shadow-sm'
                : 'text-slate-500 hover:text-slate-900'
            }`}
          >
            <Gamepad2 size={16} /> AI or Human?
          </button>
          <button
            onClick={() => setActiveMode('facts')}
            className={`flex-1 py-3 px-4 rounded-xl sm:rounded-full text-xs sm:text-sm font-black transition-all flex items-center justify-center gap-1.5 ${
              activeMode === 'facts'
                ? 'bg-[#0D47A1] text-white shadow-sm'
                : 'text-slate-500 hover:text-slate-900'
            }`}
          >
            <Lightbulb size={16} /> Fun Facts
          </button>
        </div>

        {/* Content Box */}
        <div className="max-w-3xl mx-auto min-h-[380px] bg-white rounded-3xl p-6 sm:p-10 border border-slate-200/50 shadow-md relative">
          
          <AnimatePresence mode="wait">
            
            {/* MODE 1: TRIVIA QUIZ */}
            {activeMode === 'quiz' && (
              <motion.div
                key="quiz"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="w-full flex flex-col justify-between min-h-[340px]"
              >
                {!quizFinished ? (
                  <div className="flex-1 flex flex-col justify-between">
                    <div>
                      {/* Progress Bar & Header */}
                      <div className="flex justify-between items-center mb-6 text-xs font-black text-slate-400 uppercase tracking-wider">
                        <span>Question {currentQuizIdx + 1} of {quizQuestions.length}</span>
                        <span>Score: {quizScore}</span>
                      </div>
                      
                      <h3 className="font-baloo font-black text-slate-950 text-xl sm:text-2xl mb-6 leading-snug">
                        {quizQuestions[currentQuizIdx].question}
                      </h3>

                      {/* Options Grid */}
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        {quizQuestions[currentQuizIdx].options.map((option, idx) => {
                          const isSelected = selectedOption === idx;
                          const isCorrect = idx === quizQuestions[currentQuizIdx].answerIdx;
                          let btnStyle = "border-slate-200 hover:border-slate-300 hover:bg-slate-50 text-slate-800";
                          
                          if (selectedOption !== null) {
                            if (isSelected) {
                              btnStyle = isCorrect
                                ? "bg-emerald-50 border-emerald-500 text-emerald-800"
                                : "bg-rose-50 border-[#E91E63] text-rose-800";
                            } else if (isCorrect) {
                              btnStyle = "bg-emerald-50 border-emerald-400 text-emerald-800";
                            } else {
                              btnStyle = "opacity-60 border-slate-100 text-slate-400";
                            }
                          }

                          return (
                            <button
                              key={idx}
                              disabled={selectedOption !== null}
                              onClick={() => {
                                setSelectedOption(idx);
                                if (isCorrect) {
                                  setQuizScore(prev => prev + 1);
                                }
                              }}
                              className={`p-4 rounded-2xl border-2 font-bold text-sm sm:text-base text-left transition-all flex items-center justify-between cursor-pointer ${btnStyle}`}
                            >
                              <span>{option}</span>
                              {selectedOption !== null && isCorrect && (
                                <CheckCircle2 size={20} className="text-emerald-500 shrink-0" />
                              )}
                              {selectedOption !== null && isSelected && !isCorrect && (
                                <XCircle size={20} className="text-[#E91E63] shrink-0" />
                              )}
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    {/* Feedback and Next Trigger */}
                    {selectedOption !== null && (
                      <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-8 pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
                      >
                        <p className="text-xs sm:text-sm font-semibold text-slate-500 leading-relaxed max-w-xl">
                          <strong className="text-slate-900 block sm:inline">Explanation: </strong>
                          {quizQuestions[currentQuizIdx].explanation}
                        </p>
                        
                        <button
                          onClick={() => {
                            if (currentQuizIdx + 1 < quizQuestions.length) {
                              setCurrentQuizIdx(prev => prev + 1);
                              setSelectedOption(null);
                            } else {
                              setQuizFinished(true);
                            }
                          }}
                          className="px-6 py-3 rounded-xl bg-[#E91E63] hover:bg-[#D81B60] text-white font-black text-xs uppercase tracking-wider flex items-center gap-1 transition-colors self-end sm:self-auto cursor-pointer shadow-md shadow-[#E91E6310]"
                        >
                          Next <ChevronRight size={16} />
                        </button>
                      </motion.div>
                    )}
                  </div>
                ) : (
                  // Quiz Finish Card
                  <div className="flex-1 flex flex-col items-center justify-center text-center py-6">
                    <div className="w-16 h-16 rounded-full bg-emerald-50 border-2 border-emerald-100 flex items-center justify-center text-emerald-500 mb-4 animate-bounce">
                      <Trophy size={32} />
                    </div>
                    <h3 className="font-baloo font-black text-slate-950 text-2xl mb-2">
                      Trivia Finished!
                    </h3>
                    <p className="text-slate-500 font-bold text-sm sm:text-base mb-6">
                      You scored <span className="text-[#0D47A1] font-black">{quizScore}</span> out of <span className="font-black">{quizQuestions.length}</span> correct answers!
                    </p>
                    <button
                      onClick={resetQuiz}
                      className="px-6 py-3.5 rounded-xl border-2 border-[#0D47A1] text-[#0D47A1] font-black text-xs uppercase tracking-wider flex items-center gap-2 hover:bg-blue-50/20 transition-all cursor-pointer"
                    >
                      <RefreshCw size={16} /> Retry Quiz
                    </button>
                  </div>
                )}
              </motion.div>
            )}

            {/* MODE 2: GAME (AI VS HUMAN) */}
            {activeMode === 'game' && (
              <motion.div
                key="game"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="w-full flex flex-col justify-between min-h-[340px]"
              >
                {!gameFinished ? (
                  <div className="flex-1 flex flex-col justify-between">
                    <div>
                      {/* Header */}
                      <div className="flex justify-between items-center mb-6 text-xs font-black text-slate-400 uppercase tracking-wider">
                        <span>Work {currentGameIdx + 1} of {guessItems.length}</span>
                        <span>Score: {gameScore}</span>
                      </div>

                      <div className="bg-slate-50 border border-slate-100 p-6 rounded-2xl mb-6 relative overflow-hidden">
                        <div className="absolute top-2 right-3 text-[10px] font-black uppercase text-[#00ACC1] tracking-widest">
                          {guessItems[currentGameIdx].type}
                        </div>
                        <p className="font-mono text-sm sm:text-base text-slate-800 font-bold italic leading-relaxed">
                          {guessItems[currentGameIdx].prompt}
                        </p>
                      </div>

                      <h4 className="text-slate-700 font-black text-sm uppercase tracking-wider text-center mb-6">
                        Who created this?
                      </h4>

                      {/* Game CTA choices */}
                      <div className="flex justify-center gap-4">
                        <button
                          disabled={guessAnswered !== null}
                          onClick={() => {
                            const isCorrect = guessItems[currentGameIdx].isAi;
                            setGuessAnswered(true);
                            setIsCorrectGuess(isCorrect);
                            if (isCorrect) setGameScore(prev => prev + 1);
                          }}
                          className={`flex-1 sm:flex-initial px-8 py-4 border-2 rounded-2xl font-black text-sm uppercase tracking-wider flex items-center justify-center gap-2 cursor-pointer transition-all ${
                            guessAnswered !== null
                              ? guessItems[currentGameIdx].isAi
                                ? "bg-emerald-50 border-emerald-500 text-emerald-800"
                                : guessAnswered && !isCorrectGuess
                                  ? "bg-rose-50 border-[#E91E63] text-rose-800"
                                  : "opacity-40 border-slate-100 text-slate-400"
                              : "border-slate-200 hover:border-slate-300 hover:bg-slate-50 text-slate-700"
                          }`}
                        >
                          <Bot size={18} /> 🤖 AI-Generated
                        </button>

                        <button
                          disabled={guessAnswered !== null}
                          onClick={() => {
                            const isCorrect = !guessItems[currentGameIdx].isAi;
                            setGuessAnswered(true);
                            setIsCorrectGuess(isCorrect);
                            if (isCorrect) setGameScore(prev => prev + 1);
                          }}
                          className={`flex-1 sm:flex-initial px-8 py-4 border-2 rounded-2xl font-black text-sm uppercase tracking-wider flex items-center justify-center gap-2 cursor-pointer transition-all ${
                            guessAnswered !== null
                              ? !guessItems[currentGameIdx].isAi
                                ? "bg-emerald-50 border-emerald-500 text-emerald-800"
                                : guessAnswered && !isCorrectGuess
                                  ? "bg-rose-50 border-[#E91E63] text-rose-800"
                                  : "opacity-40 border-slate-100 text-slate-400"
                              : "border-slate-200 hover:border-slate-300 hover:bg-slate-50 text-slate-700"
                          }`}
                        >
                          <User size={18} /> 🎨 Human Creator
                        </button>
                      </div>
                    </div>

                    {/* Explanations */}
                    {guessAnswered !== null && (
                      <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-8 pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
                      >
                        <p className="text-xs sm:text-sm font-semibold text-slate-500 leading-relaxed max-w-xl">
                          <strong className={`block sm:inline uppercase tracking-wide text-xs ${isCorrectGuess ? "text-emerald-600" : "text-[#E91E63]"}`}>
                            {isCorrectGuess ? "🎉 Correct! " : "❌ Incorrect! "}
                          </strong>
                          {guessItems[currentGameIdx].explanation}
                        </p>
                        
                        <button
                          onClick={() => {
                            if (currentGameIdx + 1 < guessItems.length) {
                              setCurrentGameIdx(prev => prev + 1);
                              setGuessAnswered(null);
                              setIsCorrectGuess(null);
                            } else {
                              setGameFinished(true);
                            }
                          }}
                          className="px-6 py-3 rounded-xl bg-[#E91E63] hover:bg-[#D81B60] text-white font-black text-xs uppercase tracking-wider flex items-center gap-1 transition-colors self-end sm:self-auto cursor-pointer shadow-md shadow-[#E91E6310]"
                        >
                          Next <ChevronRight size={16} />
                        </button>
                      </motion.div>
                    )}
                  </div>
                ) : (
                  // Game Finish Card
                  <div className="flex-1 flex flex-col items-center justify-center text-center py-6">
                    <div className="w-16 h-16 rounded-full bg-emerald-50 border-2 border-emerald-100 flex items-center justify-center text-emerald-500 mb-4 animate-bounce">
                      <Sparkles size={32} />
                    </div>
                    <h3 className="font-baloo font-black text-slate-950 text-2xl mb-2">
                      Guesses Complete!
                    </h3>
                    <p className="text-slate-500 font-bold text-sm sm:text-base mb-6">
                      You guessed <span className="text-[#0D47A1] font-black">{gameScore}</span> out of <span className="font-black">{guessItems.length}</span> creations correctly!
                    </p>
                    <button
                      onClick={resetGame}
                      className="px-6 py-3.5 rounded-xl border-2 border-[#0D47A1] text-[#0D47A1] font-black text-xs uppercase tracking-wider flex items-center gap-2 hover:bg-blue-50/20 transition-all cursor-pointer"
                    >
                      <RefreshCw size={16} /> Play Again
                    </button>
                  </div>
                )}
              </motion.div>
            )}

            {/* MODE 3: FACTS */}
            {activeMode === 'facts' && (
              <motion.div
                key="facts"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="w-full flex flex-col justify-between min-h-[340px]"
              >
                <div className="flex-1 flex flex-col justify-between">
                  <div>
                    {/* Header */}
                    <div className="flex justify-between items-center mb-6 text-xs font-black text-slate-400 uppercase tracking-wider">
                      <span>Fact {currentFactIdx + 1} of {facts.length}</span>
                      <span>Did you know?</span>
                    </div>

                    <div className="flex flex-col items-center text-center">
                      <div className="text-6xl mb-6 transform hover:scale-110 transition-transform duration-300 select-none">
                        {facts[currentFactIdx].emoji}
                      </div>
                      
                      <h3 className="font-baloo font-black text-slate-950 text-xl sm:text-2xl mb-4 leading-snug">
                        {facts[currentFactIdx].title}
                      </h3>
                      
                      <p className="text-slate-600 font-bold text-sm sm:text-base leading-relaxed max-w-xl mx-auto">
                        {facts[currentFactIdx].content}
                      </p>
                    </div>
                  </div>

                  {/* Fact Navigation Buttons */}
                  <div className="mt-8 pt-6 border-t border-slate-100 flex justify-center">
                    <button
                      onClick={showNextFact}
                      className="px-8 py-4 rounded-xl bg-[#E91E63] hover:bg-[#D81B60] text-white font-black text-sm uppercase tracking-wider flex items-center justify-center gap-2 transition-all hover:scale-103 cursor-pointer shadow-md shadow-[#E91E6320]"
                    >
                      Show Another Fact 🎲
                    </button>
                  </div>
                </div>
              </motion.div>
            )}

          </AnimatePresence>

        </div>

      </div>
    </section>
  );
}
